# Generated by Django 6.0.5 on 2026-06-29 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_notifications', '0001_initial'),
        ('core', '0001_initial'),
        ('financial_operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='financial_operations.enrollment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.students'),
        ),
    ]
