# Generated by Django 6.0.5 on 2026-06-29 16:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial_operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_date', models.DateField()),
                ('session_time', models.TimeField()),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'class_sessions',
                'ordering': ['session_date', 'session_time'],
                'constraints': [models.UniqueConstraint(fields=('session_date', 'session_time'), name='unique_event_datetime')],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('present', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='financial_operations.enrollment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='records.classsession')),
            ],
            options={
                'db_table': 'attendance',
                'constraints': [models.UniqueConstraint(fields=('session', 'enrollment'), name='unique_attendance_per_enrollment_per_session')],
            },
        ),
    ]
