services:
  web:
    container_name: backend
    build: .
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    restart: always

  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always

  celery:
    container_name: celery
    build: .
    env_file:
      - .env
    command: celery -A academy_q worker -l INFO
    depends_on:
      - postgres
      - redis
    restart: always

  celery-beat:
    container_name: celery-beat
    build: .
    env_file:
      - .env
    command: celery -A academy_q beat -l INFO
    depends_on:
      - postgres
      - redis
    restart: always

volumes:
  postgres_data: