# Generated by Django 6.0.5 on 2026-06-29 16:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('financial_operations', '0001_initial'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.academy')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('session_count', models.IntegerField(default=1, help_text='Total planned sessions for this class delivery')),
                ('session_price', models.DecimalField(decimal_places=2, default=0, help_text='Price per single session.', max_digits=10)),
                ('session_duration', models.DurationField(default='01:00:00', help_text='Duration of each session e.g. 01:30:00')),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.academy')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='structure.subject')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'db_table': 'classes',
                'ordering': ['academy', 'subject', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='TeacherClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateField()),
                ('assigned_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='structure.class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='financial_operations.teachers')),
            ],
            options={
                'verbose_name': 'Teacher Class',
                'verbose_name_plural': 'Teacher Classes',
                'db_table': 'teacher_classes',
                'ordering': ['assigned_class', 'teacher', 'assigned_at'],
            },
        ),
        migrations.AddField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(related_name='classes', through='structure.TeacherClass', to='financial_operations.teachers'),
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, editable=False, null=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='structure.class')),
            ],
            options={
                'verbose_name': 'Class Schedule',
                'verbose_name_plural': 'Class Schedules',
                'db_table': 'class_schedules',
                'constraints': [models.UniqueConstraint(fields=('class_obj', 'day_of_week', 'start_time'), name='unique_class_slot')],
            },
        ),
        migrations.CreateModel(
            name='ClassSessionEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_num', models.IntegerField(help_text='Sequential session number within this class.')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_links', to='structure.class')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_links', to='records.classsession')),
            ],
            options={
                'verbose_name': 'Class Session Enrollment',
                'verbose_name_plural': 'Class Session Enrollments',
                'db_table': 'class_session_enrollments',
                'constraints': [models.UniqueConstraint(fields=('session', 'class_obj'), name='unique_session_per_class'), models.UniqueConstraint(fields=('class_obj', 'session_num'), name='unique_session_num_per_class')],
            },
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('academy', 'name'), name='unique_subject_name_per_academy'),
        ),
        migrations.AddConstraint(
            model_name='teacherclass',
            constraint=models.UniqueConstraint(fields=('assigned_class', 'teacher'), name='unique_teacher_per_class'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('academy', 'subject', 'name'), name='unique_class_name_per_subject_academy'),
        ),
    ]
