# Generated by Django 6.0.5 on 2026-07-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='session_count',
            field=models.IntegerField(help_text='Total planned sessions for this class delivery'),
        ),
        migrations.AlterField(
            model_name='class',
            name='session_price',
            field=models.DecimalField(decimal_places=2, help_text='Price per single session.', max_digits=10),
        ),
    ]
