# Generated by Django 6.0.5 on 2026-06-29 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
        ('core', '0001_initial'),
        ('financial_operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='financial_operations.enrollment'),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='academy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='core.academy'),
        ),
    ]
