# Generated by Django 6.0.5 on 2026-06-14 11:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial_operations', '0007_payment_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReportCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=7)),
                ('summary_text', models.TextField()),
                ('risk_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('risk_score', models.IntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='financial_operations.enrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Report Card',
                'verbose_name_plural': 'AI Report Cards',
                'db_table': 'ai_report_cards',
                'ordering': ['-generated_at'],
                'unique_together': {('enrollment', 'month')},
            },
        ),
    ]
