# Generated by Django 6.0.5 on 2026-06-29 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('financial_operations', '0001_initial'),
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='class_id',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='structure.class'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='core.students'),
        ),
        migrations.AddField(
            model_name='payment',
            name='enrollment_id',
            field=models.ForeignKey(db_column='enrollment_id', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='financial_operations.enrollment'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='academy_id',
            field=models.ForeignKey(db_column='academy_id', on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='core.academy'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='user_id',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student_id', 'class_id')},
        ),
    ]
