# Generated by Django 6.0.5 on 2026-06-29 16:49

import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0000_extensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature', models.CharField(choices=[('report_card', 'Report Card'), ('risk_score', 'Risk Score'), ('payment_reminder', 'Payment Reminder'), ('management_report', 'Management Report'), ('embedding', 'Embedding')], max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('prompt_token', models.IntegerField(default=0)),
                ('completion_token', models.IntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=6, max_digits=10)),
                ('succeeded', models.BooleanField(default=True)),
                ('cache_hit', models.BooleanField(default=False)),
                ('called_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-called_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=3072)),
                ('source_text', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
