# Generated by Django 6.0.5 on 2026-06-29 16:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True)),
                ('subscription_end', models.DateField(null=True)),
                ('setup_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('weekly_report_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Academy',
                'db_table': 'academy',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('O', 'Owner'), ('A', 'Admin'), ('T', 'Teacher'), ('S', 'Student')], max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('academy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academy_user', to='core.academy')),
            ],
            options={
                'verbose_name': 'User',
                'db_table': 'users',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_email', models.EmailField(blank=True, max_length=254)),
                ('educational_level', models.IntegerField(choices=[(1, 'Primary 1'), (2, 'Primary 2'), (3, 'Primary 3'), (4, 'Primary 4'), (5, 'Primary 5'), (6, 'Primary 6'), (7, 'Preparatory 1'), (8, 'Preparatory 2'), (9, 'Preparatory 3'), (10, 'Secondary 1'), (11, 'Secondary 2'), (12, 'Secondary 3'), (13, 'College 1'), (14, 'College 2'), (15, 'College 3'), (16, 'College 4'), (17, 'College 5'), (18, 'College 6')], null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('D', 'Dropped')], default='P', max_length=10)),
                ('enrolled_at', models.DateField(blank=True, null=True)),
                ('academy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academy_student', to='core.academy')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'S'}, on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Students',
                'db_table': 'students',
            },
        ),
    ]
